#!/bin/bash

ANDROID_TOP_DIR="/home/zeroway/3288/51/src/3288_5.1_v2"
ANDROID_OUT_DIR="$ANDROID_TOP_DIR/out/target/product/rk3288"
IMAGE_PATH="$ANDROID_TOP_DIR/rockdev/Image-rk3288"
RAMDISK_IMG="ramdisk.img"
BOOT_IMG="boot.img"

# utils
MKBOOTFS="$ANDROID_TOP_DIR/out/host/linux-x86/bin/mkbootfs"
RK_MKKRNLIMG="$ANDROID_TOP_DIR/rkst/mkkrnlimg"

$MKBOOTFS $ANDROID_OUT_DIR/root | minigzip > $ANDROID_OUT_DIR/$RAMDISK_IMG && \
	truncate -s "%4" $OUT/$RAMDISK_IMG && \
$RK_MKKRNLIMG $OUT/$RAMDISK_IMG $IMAGE_PATH/$BOOT_IMG >/dev/null
