#!/bin/bash

# global variable
ANDROID_TOP_DIR="/home/zeroway/3288/51/src/3288_5.1_v2"

ANDROID_OUT_DIR="$ANDROID_TOP_DIR/out/target/product/rk3288"
HOST_BIN="$ANDROID_TOP_DIR/out/host/linux-x86/bin"
BUILD_IMAGE_SCRIPT="$ANDROID_TOP_DIR/build/tools/releasetools/build_image.py"
SYSTEM_OUTPUT_DIR="$ANDROID_OUT_DIR/obj/PACKAGING/systemimage_intermediates"

PATH=$HOST_BIN:$PATH
$BUILD_IMAGE_SCRIPT $ANDROID_OUT_DIR/system $SYSTEM_OUTPUT_DIR/system_image_info.txt $SYSTEM_OUTPUT_DIR/system.img

$HOST_BIN/acp -fp $SYSTEM_OUTPUT_DIR/system.img $ANDROID_OUT_DIR/system.img
