#!/bin/bash

# marco
ANDROID_TOP_DIR="/home/zeroway/rk3399/src"
KERNEL_OUT_DIR="$ANDROID_TOP_DIR/out/target/product/rk3399_firefly_box/obj/KERNEL"
UBOOT_OUT_DIR="$ANDROID_TOP_DIR/out/target/product/rk3399_firefly_box/obj/UBOOT"

# update.img out dir
UPDATES_GEN_DIR="/home/zeroway/rk3399/bsp/updates"

CURRENT_DATE=`date +%Y%m%d`

# pack images
pack_images()
{
	cp $TARGET_PARAMETER_FILE $UPDATES_GEN_DIR/Image/
	$UPDATES_GEN_DIR/afptool -pack $UPDATES_GEN_DIR/ $UPDATES_GEN_DIR/Image/update.img || pause
	$UPDATES_GEN_DIR/rkImageMaker $PLATFORM $TARGET_BOOTLOADER_IMG $UPDATES_GEN_DIR/Image/update.img "update_${SOC_NAME}_${ANDROID_VERSION}_${CURRENT_DATE}_linux.img" -os_type:androidos || pause
}

# make links
make_links()
{
	# clean the Image directory
	rm -rvf $UPDATES_GEN_DIR/Image
	mkdir -p $UPDATES_GEN_DIR/Image

	# make links files to target
	cd $UPDATES_GEN_DIR/Image/
	for file in ${target_imgs[@]}
	do
		ln -s $file
	done
	cd $UPDATES_GEN_DIR/
}

make_update_3399()
{
	# 3399 target images
	TARGET_KERNEL_IMG="$KERNEL_OUT_DIR/kernel.img"
	TARGET_RESOURCE_IMG="$KERNEL_OUT_DIR/resource.img"
	TARGET_RECOVERY_IMG="$ANDROID_TOP_DIR/rockdev/Image-rk3399_firefly_box/recovery.img"
	TARGET_SYSTEM_IMG="$ANDROID_TOP_DIR/rockdev/Image-rk3399_firefly_box/system.img"
	TARGET_BOOT_IMG="$ANDROID_TOP_DIR/rockdev/Image-rk3399_firefly_box/boot.img"
	TARGET_MISC_IMG="$ANDROID_TOP_DIR/rockdev/Image-rk3399_firefly_box/misc.img"
	TARGET_TRUST_IMG="$UBOOT_OUT_DIR/trust.img"
	TARGET_PACKAGE_FILE="$UPDATES_GEN_DIR/package-file"
	TARGET_PARAMETER_FILE="$UPDATES_GEN_DIR/parameter.txt"
	TARGET_UBOOT_IMG="$UBOOT_OUT_DIR/uboot.img"
	TARGET_BOOTLOADER_IMG="$UBOOT_OUT_DIR/RK3399MiniLoaderAll_V1.05.bin"
	target_imgs=(
		$TARGET_KERNEL_IMG
		$TARGET_RESOURCE_IMG
		$TARGET_RECOVERY_IMG
		$TARGET_SYSTEM_IMG
		$TARGET_BOOT_IMG
		$TARGET_MISC_IMG
		$TARGET_TRUST_IMG
		$TARGET_UBOOT_IMG
		$TARGET_BOOTLOADER_IMG
	)

	# make links for the metadata
	make_links

	echo "make 3399 6.0 update.img"
	PLATFORM="-RK330C"
	SOC_NAME="3399"
	ANDROID_VERSION="6.0"
	pack_images
}

make_update_3399
